### ISSUE TITLE
Failed to download the CheckStyle

### ISSUE THREAD

**Issue by rshkv** [jdneo/vscode-checkstyle#124]
Hi @jdneo,

Just installed CheckStyle yesterday, but getting a 
```
Failed to download the CheckStyle, please try again later.
```

Nothing in the checkstyle output. Anything I can try?

**Comment by rshkv** [comment]
(Download the jar myself worked.)

**Comment by jdneo** [comment]
Yes that’s because the checkstyle team no longer use the sourceforge to host binaries any more. I have just released a new version 0.5.1 to fix this. Could you please have a try?

**Comment by rshkv** [comment]
@jdneo, sure you released?

**Comment by jdneo** [comment]
Did you set the version setting? Or it’s using default value, which is 8.0

**Comment by rshkv** [comment]
Yeah. Still seeing the error. Where can I see the logs for this?

**Comment by jdneo** [comment]
Emm... You can click `Help` > `Toggle Developer Tools` to see if there is anything in the console.

BTW, can you access this link: https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.0/checkstyle-8.0-all.jar?

**Comment by rshkv** [comment]
You can close this. I think it might be related to my company's network. It worked in another network. Thanks for looking into this @jdneo.

**Comment by jdneo** [comment]
@rshkv Glad to know the problem have been solved. 😄

**Comment by nanliu** [comment]
@jdneo thanks, I missed the second half of the comment where "checkstyle.version" accepts version and path to jar file.
